apiVersion: apps/v1
kind: Deployment
metadata:
  name: chineese
  namespace: chineese-os-system-com-${ENV}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chineese
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chineese
    spec:
      containers:
      - image: ${IMAGE_NAME}
        imagePullPolicy: Always
        name: chineese

